= os--char-dev--lkm
:toc:

_**O**perating **S**ystems, **Char**acter **Dev**ice, **L**oadable **K**ernel **M**odule_

This is a character device gets system information from kernel space, and returns it as a byte stream of JSON.

There is a userspace application that is a demo of this. The link to that is on this repo under the the About section on the sidebar.

== Usage

=== read()

Read the current value of the <<current-info-type, current_info_type>> from the module.

=== ioctl()

Change the current_info_type returned from the module.

[[currnt-info-type]]
== current_info_type

This is the single sysinfo value that is returned from the module. The available sysinfo types are:

1. cpu
2. disk
3. memory

You can toggle between these info types using this device's ioctl() function, and it's commands.

== Install

Clone this repo.

[source, bash]
----
git clone git@github.com:mikeyfennelly1/os--char-dev--lkm.git
----

Install dependencies.

[source, bash]
----
sudo make install
----

== Buid and insert kernel object file.

=== Build.

[source, bash]
----
make
----

When you run make, there will be a new directory _./build_, and a subdirectory _./build/k_ojbs_. This directory contains the kernel object (.ko) file for the module.

=== Insert

[source, bash]
----
sudo insmod ./build/sysinfo.ko
----

=== Verify module load

The following command will print the name of the kernel module if it is inserted.

[source, bash]
----
lsmod | grep sys
----
