= job.h
:toc:

A job is a data structure that you can use to create sysinfo 'jobs'.

== What is the Job API?

You can use the job API to create a set of sysinfo steps. It allows you to just have to worry about getting the data, and adding it to the job. The job API handles the rest (string formatting, outputting the contents etc).

The *user of the job API needs to be aware of 3 data structures*.

*The Job API provides 3 main data structures:*

1. Job (highest level data structure)

[source, c]
----
typedef struct Job {
    // title for the job
    char* job_title;

    // The 'head' step is the first step to
    // run in the job
    Step* head;
} Job;
----

2. Step (a component of a Job)

[source, c]
----
typedef struct Step {
    // see job.h for implementation if needed.
} Step;
----

3. key_value_pair (the data structure obtained by a Step)

[source, c]
----
typedef struct key_value_pair {
    char* key;
    char* value;
} key_value_pair;
----


Basically, a Job is a list of Steps. This data structure provides a simple API to create a set of ordered steps to retrieve sysinfo from kernel space.

Methods in the job API can be used to:

1. Create Steps
2. Create Jobs
3. Add Steps to Jobs
4. Run those jobs - returning a string.

== How to create a job

=== 1. Include job.h

Firstly, include the job header file in your module's _.c_ file.

[source, c]
----
#include "./job.h"
----

=== 2. Create the first step for the job

1. Create the function that runs during this step.

[source, c]
----
key_value_pair my_sysinfo_function(void)
{
    key_value_pair my_data;

    // ... your code here ...

    return my_data;
}
----

2. Create a high level function that will create your job when called.

[source, c]
----
Job* get_my_job(void)
{
    // create the name for your job
    char* my_job_title = "my_sysinfo_category";

    // create the job via address of the function
    // you want to start with
    Job* my_job = job_init(my_job_title, &my_sysinfo_function);

    // ... add some more sysinfo functions to the job ...
    append_step_to_job(job, &my_second_function);
    append_step_to_job(job, &my_third_function);
    // ... etc
    return my_job;
}
----

And that is it, that is all you have to do to create a Job.